function M = plane3AnalyticalMass(rho,t,x)
%PLANE3ANALYTICALMASS
%    M = PLANE3ANALYTICALMASS(RHO,T,X_I,X_J,X_K,Y_I,Y_J,Y_K)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    15-Jun-2016 17:14:17

x_i = x(1,1);
x_j = x(2,1);
x_k = x(3,1);
y_i = x(1,2);
y_j = x(2,2);
y_k = x(3,2);

t2 = x_i.*y_j;
t3 = x_k.*y_i;
t4 = x_j.*y_k;
t6 = x_j.*y_i;
t7 = x_i.*y_k;
t8 = x_k.*y_j;
t5 = t2+t3+t4-t6-t7-t8;
t9 = rho.*t.*t5.*(1.0./2.4e1);
t10 = rho.*t.*t5.*(1.0./1.2e1);
M = reshape([t10,0.0,t9,0.0,t9,0.0,0.0,t10,0.0,t9,0.0,t9,t9,0.0,t10,0.0,t9,0.0,0.0,t9,0.0,t10,0.0,t9,t9,0.0,t9,0.0,t10,0.0,0.0,t9,0.0,t9,0.0,t10],[6,6]);
